Delete output directory just before generating it
alexcanessa/typescript-coverage-report pull request #46
Opened 2021-01-24 14:03 UTC by cabello

Hello 👋 

The report data collection & generation may take seconds to minutes.

I noticed that as soon as I trigger the coverage command, I am unable to navigate the previous report because it gets deleted.

This change delays the deletion of the file to just before generating the HTML report, allowing developers to explore the previous report while a new one is being generated.

Thank you 💜

2021-01-25 10:15 UTC, alexcanessa requested changes
Hello @cabello thanks for your contribution.

The only request is change the commit to follow the [guidance](https://github.com/alexcanessa/typescript-coverage-report#commit-messages).

In your case, something like this would work:

```
fix: allow exploring previous report while generating the new one
```

2021-01-25 10:16 UTC, alexcanessa commented
@all-contributors add @cabello for code

2021-01-25 13:15 UTC, cabello commented
Done 🙇

2021-01-26 13:06 UTC, alexcanessa approved these changes

2021-01-26 13:06 UTC, merged